#!/bin/bash

set -euxo pipefail

time curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly-2020-07-27 -y

echo '. $HOME/.cargo/env' >> ~/.bashrc
echo '. $HOME/.cargo/env' >> ~/.profile
source $HOME/.cargo/env

time cargo install evcxr_jupyter
time evcxr_jupyter --install

# Share our build directory between all executions.
# See https://github.com/google/evcxr/issues/52#issuecomment-520266256
export EVCXR_TMPDIR=$HOME/evcxr_build

# Pre-populate build directory as part of the docker image.
time cargo install  evcxr_repl
time echo ':dep arrow = "1.0"' | evcxr > /dev/null
time echo ':dep polars = "0.2"' | evcxr > /dev/null
