#!/bin/bash

set -euxo pipefail

# Share our build directory between all executions.
# See https://github.com/google/evcxr/issues/52#issuecomment-520266256
mkdir $HOME/evcxr_build
export EVCXR_TMPDIR=$HOME/evcxr_build

# workaround for this error:
# error: current package believes it's in a workspace when it's not:
# current:   /home/alsuren/evcxr_build/Cargo.toml
# workspace: /home/alsuren/Cargo.toml
rm $HOME/Cargo.toml

echo '
export EVCXR_TMPDIR=$HOME/evcxr_build
source $HOME/.cargo/env
' >> ~/.bashrc
echo '
export EVCXR_TMPDIR=$HOME/evcxr_build
source $HOME/.cargo/env
' >> ~/.profile

# FIXME: work out a way to pin to a specific version of nightly, for reproducibility.
# Annoyingly :time_passes requires the toolchain to be called `nightly` and not
# nightly-2020-07-27 ("error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed")
time curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly -y
source $HOME/.cargo/env

time cargo install sccache
time cargo install evcxr_jupyter
time evcxr_jupyter --install

time cargo install evcxr_repl

# Pre-populate build directory as part of the docker image.
time echo ':help
:time_passes
:timing
:linker
:dep arrow = "1.0"
' | evcxr
